title: 'coding test #1'
description: first time coding heads up
template:
  repo: coding-test-1-template
  name: coding-test-1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
